name: 'monzo_analytics'
version: '1.0.0'
config-version: 2

# Perfil que você configurou no seu profiles.yml
profile: 'monzo_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuração de Modelos
models:
  monzo_analytics: # Deve ser IGUAL ao 'name' lá no topo do arquivo
    
    # Camada Staging: Leve, apenas limpeza. Sempre View.
    staging:
      +materialized: view
    
    # Camada Intermediate: Transformação pesada. View ou Ephemeral.
    intermediate:
      +materialized: view

    # Camada Marts: Onde os analistas consultam. Sempre Table para performance.
    marts:
      +materialized: table
      
      # Configurações específicas para a Fato (Task 2)
      # Se o seu arquivo fct_user_activity_daily estiver dentro de uma subpasta chamada 'fct'
      fct: 
        +partition_by:
          field: reference_date
          data_type: date
          granularity: day
